version: '3.7'

services:

  front_end:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      CLIENTE_SERVICIOS_USR: prueba
      CLIENTE_SERVICIOS_PWD: AlfaOmega2020
      URL_SERVICIOS: http://tucanes.ddns.net:8080
      LLAVE_AES: ${LLAVE_AES}
    build: .
    restart: always
    container_name: front_end_segura
    volumes:
      - ./progra_segura:/code
    depends_on:
      - bd
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "250M"

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./progra_segura/static:/static
      - /etc/letsencrypt/archive/tucanes.ddns.net:/certs 
     # - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front_end
    ports:
      - 8000:443

  bd:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - /home/tucanesalv/data:/var/lib/mysql

