# Generated by Django 3.0.2 on 2020-06-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('ultima_peticion', models.DateTimeField()),
                ('intentos', models.IntegerField(default=0)),
            ],
        ),
    ]
