# Generated by Django 3.0.2 on 2020-07-05 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('ultima_peticion', models.DateTimeField()),
                ('intentos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='servers',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='client_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_servidor', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='bd.servers')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
