# Generated by Django 3.0.2 on 2020-07-07 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bd', '0002_auto_20200706_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_server',
            old_name='ip_servidor',
            new_name='url_servicios',
        ),
        migrations.RenameField(
            model_name='servers',
            old_name='ip',
            new_name='url_servicios',
        ),
        migrations.CreateModel(
            name='registrar_contraseña',
            fields=[
                ('contraseña', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
