# Generated by Django 3.0.2 on 2020-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_auto_20200707_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='url_servicios',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
