# Generated by Django 3.0.2 on 2020-07-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_auto_20200707_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_contraseña',
            name='contraseña',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registrar_contraseña',
            name='usuario',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
