# Generated by Django 3.0.2 on 2020-07-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_auto_20200708_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_contraseña',
            name='contraseña',
            field=models.CharField(max_length=50),
        ),
    ]
