# Generated by Django 3.0.2 on 2020-07-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0006_auto_20200708_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servers',
            name='nombre',
        ),
        migrations.AddField(
            model_name='servers',
            name='contraseña',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servers',
            name='iv',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='servers',
            name='usuario',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
